# Generated by Django 3.2 on 2024-10-01 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='confirmation_code',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Код подтверждения'),
        ),
    ]
