# Generated by Django 3.2 on 2024-10-01 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_myuser_confirmation_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='confirmation_code',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Код подтверждения'),
        ),
    ]
